apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: wp-mysql
  labels: 
    name: wp-mysql-service
    app: wordpress-app-demo-kube   
spec: 
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 31006
  type: NodePort
  selector:
    name: wordpress-mysql-deployment
    app: wordpress-app-demo-kube
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql-deployment
  labels:
    app: wordpress-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress-mysql-deployment
      app: wordpress-app-demo-kube 
  template:
    metadata:
      name: wp-mysql
      labels: 
        name: wordpress-mysql-deployment
        app: wordpress-app-demo-kube   
    spec: 
      containers:
      - name: wp-app
        image: harbor.jojonomic.io/jojolab/wp-mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim