
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app-deployment
  labels:
    name: wordpress-app-deployment
    app: wordpress-app-demo-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress-app-deployment
      app: wordpress-app-demo-kube
  template:
    metadata:
      name: wordpress-deployment
      labels: 
        name: wordpress-app-deployment
        app: wordpress-app-demo-kube   
    spec: 
      containers:
      - name: wp-app
        image: harbor.jojonomic.io/jojolab/wordpress
        ports:
        - containerPort: 80
        
--- 

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels: 
    name: wordpress-service
    app: wordpress-app-demo-kube   
spec: 
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31100
  type: NodePort
  selector:
    name: wordpress-app-deployment
    app: wordpress-app-demo-kube

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql-deployment
  labels:
    app: wordpress-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress-mysql-deployment
      app: wordpress-app-demo-kube 
  template:
    metadata:
      name: wp-mysql
      labels: 
        name: wordpress-mysql-deployment
        app: wordpress-app-demo-kube   
    spec: 
      containers:
      - name: wp-app
        image: harbor.jojonomic.io/jojolab/wp-mysql
        ports:
        - containerPort: 3306
        
        
--- 

apiVersion: v1
kind: Service
metadata:
  name: wp-mysql
  labels: 
    name: wp-mysql-service
    app: wordpress-app-demo-kube   
spec: 
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 31001
  type: NodePort
  selector:
    name: wordpress-mysql-deployment
    app: wordpress-app-demo-kube

